name: Cover
on:
  # Allow the workflow to be triggered manually using the GitHub API, CLI, or browser interface
  workflow_dispatch:
  # Trigger the workflow automatically on pushes to main
  push:
    branches: [ main ]
concurrency:
  # Only allow one run of the workflow per branch to run at a time
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: windows-latest
    env:
      JVM_ARGS: -Xmx4096m
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize Gradle build
        run: gradle init
      - name: Compile project
        run: gradle build
      # Get, unzip, and activate Diffblue Cover
      - name: Download Diffblue Cover
        run: |
          mkdir -p "$RUNNER_TEMP/dcover"

          cd "$RUNNER_TEMP/dcover"

      - name: Redownload Diffblue Cover CLI zip file
        run: |
          curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://newsletters.diffblue.com/e3t/Ctc/DM+113/cSDxS04/VWqNRd1clLLkW29N02L52_D-RW5d86_w552HsPMGxfTK5m_5PW6N1X8z6lZ3m1W8lCX8k3x0JxHW2L4GXW66vzPWW5h4tY84P7Sy6W3Nf-ML9cCJ6nW7DH40d25CxDGN3trsz-zbqSGW6bG4M_1pqFB3W58Z-YT7Cg1fbW33GxMg4F3gB0W1d7JVm1Xy7B5W5mQpHM70tCzcW1RL-qN8nTGL0W1qhjhq3WPq1QW4kbd608TTQBMW1hKQM16hwhdfW3-46XM6RW1BdW6qSFvx2l-hNRW5yt71b8CYl2JW3fgHMF3K214gW65P5K95zrHl6W67b2V98yjMq0W54fRpq22VmHdW8w6Htp3qNXqXW1ggrxx1gHtFtW8YslSg7m7T3LN90_kT91QdY0VwtYMH7ydYCxMFLL_Cq5m0jW67Zslb46lbZMW7Tw9ML34YC15W33KT991wMgTFW5KbwNC6BdXqlW6Mbnnd3kfJJwW4WhnTX63Nc9pW3K-FC2313h3CW8zjwYH2qH49sW6V30_B8s8-1FW1KS0b76wWwGhf1YzG9z04"

      - name: Print the list of dir
        run: |
          ls

      - name: change dir
        run: |
          cat diffblue-cover-cli.zip   

      - name: Unzip Diffblue Cover CLI zip file
        run: |
          unzip diffblue-cover-cli.zip

      - name: Remove Diffblue Cover CLI zip file
        run: |
          Remove-Item -Path "diffblue-cover-cli.zip" -Force

      - name: Add Diffblue Cover directory to GITHUB_PATH
        run: |
          echo "$RUNNER_TEMP/dcover" >> "$GITHUB_PATH"

      - name: Activate Diffblue Cover
        run: |
          dcover activate "${{ secrets.DIFFBLUE_COVER_LICENSE_KEY }}"

      # Generate tests with Diffblue Cover
      - name: Generate tests
        run: |
          dcover create org.example.Addition --batch --working-directory --output test-cases.java
