name: SpringBoot CI Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
            repository: Riyagharde/DemoProject
            ref: main

     - name: Initialize Gradle build
       run: |
            gradle init

     - name: Compile project
       run: |
            gradle build
            
     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
          java-version: 17
          distribution: 'temurin'
          
     - name: Build and test with Gradle
       run: C:\diffblue-project\student-management-system-springboot\gradlew.bat build test 
        
     - name: Check test results
       run: C:\diffblue-project\student-management-system-springboot\gradlew.bat test --scan --info
        
     - name: Check code coverage
       run: C:\diffblue-project\student-management-system-springboot\gradlew.bat jacocoTestReport --outputText
       if: success()
     - name: Fail if coverage is below 75%
       if: steps.check_coverage.outputs.coverage < 75
       run: exit 1
