name: Cover
on:
  # Allow the workflow to be triggered manually using the GitHub API, CLI, or browser interface
  workflow_dispatch:
  # Trigger the workflow automatically on pushes to main
  push:
    branches: [ main ]
concurrency:
  # Only allow one run of the workflow per branch to run at a time
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: windows-latest
    env:
      JVM_ARGS: -Xmx4096m
    steps:
          - name: Set Environment Path Variable for Dcover directory
            uses: myci-actions/append-to-path-windows@2
            with:
              path: D:\a\DemoProject\DemoProject\Diffblue\dcover
              env-var: PATH

          - name: Checkout repository
            uses: actions/checkout@v3
            with:
                repository: Riyagharde/DemoProject
                ref: main

          - name: Initialize Gradle build
            run: |
               gradle init

          - name: Compile project
            run: |
              gradle build

              # Get, unzip, and activate Diffblue Cover
          - name: Create demo/decover dir and Download Diffblue Cover into this dir
            run: |
                mkdir Diffblue/dcover

          - name: Redownload Diffblue Cover CLI zip files
            run: |
                curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://release.diffblue.com/2023.10.01/88bd072f1e783483a53e1fa7e53511d57b64a3b64e6f618c624f5a990409262f/diffblue-cover-cli-2023.10.01.zip"

          - name: Print the list of dir
            run: |
              ls
              pwd

          - name: print the content
            run: |
              cat diffblue-cover-cli.zip   

          - name: Unzip Diffblue Cover CLI zip file
            run: |
              unzip diffblue-cover-cli.zip -d Diffblue/dcover

          - name: list the directories
            run: |
              ls Diffblue/dcover


          - name: Activate Diffblue Cover
            run: |
              dcover activate H532-DV4M-B4SJ-WYCO
            working-directory: D:\a\DemoProject\DemoProject\Diffblue\dcover

          # Generate tests with Diffblue Cover
          - name: Generate tests
            run: |    
              dcover create org.example.Addition --batch --working-directory --output Test-cases.java
            working-directory: D:\a\DemoProject\DemoProject\Diffblue